-- DDL

CREATE SCHEMA book_store;

USE book_store;

CREATE TABLE book
(
    id BIGINT UNSIGNED AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    author VARCHAR(50) NOT NULL,
    barcode VARCHAR(13) NOT NULL UNIQUE,
    quantity INT UNSIGNED,
    price_per_unit DOUBLE(10,2) NOT NULL,
    PRIMARY KEY (id, barcode)
);

CREATE TABLE antique_book
(
    id BIGINT UNSIGNED AUTO_INCREMENT,
    CONSTRAINT PK_ANTIQUE PRIMARY KEY (id),
    CONSTRAINT FK_ANTIQUE_BOOK FOREIGN KEY (id) REFERENCES book (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    release_year INT NOT NULL
);

CREATE TABLE science_journal
(
    id BIGINT UNSIGNED AUTO_INCREMENT,
    CONSTRAINT PK_JOURNAL PRIMARY KEY (id),
    CONSTRAINT FK_JOURNAL_BOOK FOREIGN KEY (id) REFERENCES book (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    science_index TINYINT NOT NULL
);